service: trustyGetAddrData
provider:  
    name: aws  
    runtime: nodejs12.x  
    stage: dev  
    region: us-east-2
functions:
  server:
    handler: src/aws-server/index.handler # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: false
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: false
      - http: # all routes get proxied to the Express router
          path: /checkup
          method: GET
          cors: false 